# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aphw-ddi-enforcement:
    build:
      target: development
    image: aphw-ddi-enforcement-development
    container_name: aphw-ddi-enforcement-development
    ports:
      - "3003:3000"
      - "9232:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}

