# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  aphw-ddi-enforcement:
    build:
      target: development
    image: aphw-ddi-enforcement-development
    container_name: aphw-ddi-enforcement-test
    command: npm run test:parallel
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    environment:
      DDI_API_BASE_URL: test
      DDI_EVENTS_BASE_URL: test-events