services:
  aphw-ddi-enforcement:
    build:
      context: .
      target: production
    image: aphw-ddi-enforcement
    container_name: aphw-ddi-enforcement
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-enforcement-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      DDI_API_BASE_URL: ${DDI_API_BASE_URL:-test}
      DDI_EVENTS_BASE_URL: ${DDI_EVENTS_BASE_URL:-test}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      AZUREID_CLIENT_SECRET: ${AZUREID_CLIENT_SECRET}
      AZUREID_CLIENT_ID: ${AZUREID_CLIENT_ID}
      AZUREID_TENANT_ID: ${AZUREID_TENANT_ID}
      REDIRECT_URL: ${REDIRECT_URL}
