services:
  aphw-ddi-enforcement:
    build:
      context: .
      target: production
    image: aphw-ddi-enforcement
    container_name: aphw-ddi-enforcement
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-enforcement-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      DDI_API_BASE_URL: ${DDI_API_BASE_URL:-test}
      DDI_EVENTS_BASE_URL: ${DDI_EVENTS_BASE_URL:-test}
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-test}
      OS_PLACES_API_BASE_URL: ${OS_PLACES_API_BASE_URL:-test}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      REDIRECT_URL: ${REDIRECT_URL}
      POST_LOGOUT_URL: ${POST_LOGOUT_URL}
      OPENID_DISCOVERY_ENDPOINT: ${OPENID_DISCOVERY_ENDPOINT}
      OPENID_PRIVATE_KEY: ${OPENID_PRIVATE_KEY}
      OPENID_PUBLIC_KEY: ${OPENID_PUBLIC_KEY}
      OPENID_CLIENT_ID: ${OPENID_CLIENT_ID}
      AUTHENTICATION_ENABLED: ${AUTHENTICATION_ENABLED}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
