{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-enforcement.config-map") -}}
{{- define "aphw-ddi-enforcement.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.pr }}
  REDIRECT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/authenticate
  POST_LOGOUT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/post-logout
  {{ else }}
  REDIRECT_URL: {{ quote .Values.container.redirectUrl }}
  POST_LOGOUT_URL: {{ quote .Values.container.postLogoutUrl }}
  {{- end }}
  OPENID_DISCOVERY_ENDPOINT: {{ quote .Values.container.openidDiscoveryEndpoint }}
  AUTHENTICATION_ENABLED: "true"
  DDI_API_BASE_URL: {{ quote .Values.container.ddiApiBaseUrl }}
  DDI_EVENTS_BASE_URL: {{ quote .Values.container.ddiEventsBaseUrl }}
  OS_PLACES_API_BASE_URL: {{ quote .Values.container.osPlacesBaseUrl }}
{{- end -}}
