{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-enforcement.config-map") -}}
{{- define "aphw-ddi-enforcement.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.pr }}
  REDIRECT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/authenticate
  POST_LOGOUT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/post-logout
  {{ else }}
  REDIRECT_URL: {{ quote .Values.container.redirectUrl }}
  POST_LOGOUT_URL: {{ quote .Values.container.postLogoutUrl }}
  {{- end }}
  {{- if and (.Values.environmentCode) (not .Values.pr) }}
  DOCUMENT_REQUEST_QUEUE: {{ .Values.container.documentRequestQueue }}-{{ .Values.environmentCode }}
  {{ else }}
  DOCUMENT_REQUEST_QUEUE: {{ quote .Values.container.documentRequestQueue }}
  {{- end }}
  OPENID_DISCOVERY_ENDPOINT: {{ quote .Values.container.openidDiscoveryEndpoint }}
  AUTHENTICATION_ENABLED: "true"
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  DDI_API_BASE_URL: {{ quote .Values.container.ddiApiBaseUrl }}
  DDI_EVENTS_BASE_URL: {{ quote .Values.container.ddiEventsBaseUrl }}
  OS_PLACES_API_BASE_URL: {{ quote .Values.container.osPlacesBaseUrl }}
  REDIS_HOSTNAME: {{ quote .Values.container.redisHostname }}
  REDIS_PORT: {{ quote .Values.container.redisPort }}
{{- end -}}
