{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-enforcement.config-map") -}}
{{- define "aphw-ddi-enforcement.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.pr }}
  REDIRECT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/{{ .Values.azureAppRegistration.redirectUrl }}
  POST_LOGOUT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/{{ quote .Values.container.postLogoutRoute }}
  {{ else }}
  REDIRECT_URL: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}/{{ .Values.azureAppRegistration.redirectUrl }}
  POST_LOGOUT_URL: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}/{{ quote .Values.container.postLogoutRoute }}
  {{- end }}
  AUTHENTICATION_ENABLED: {{ quote .Values.azureAppRegistration.enabled }}
  DDI_API_BASE_URL: {{ quote .Values.container.ddiApiBaseUrl }}
  DDI_EVENTS_BASE_URL: {{ quote .Values.container.ddiEventsBaseUrl }}
{{- end -}}
