{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-enforcement.container-secret") -}}
{{- define "aphw-ddi-enforcement.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  OPENID_CLIENT_ID: {{ quote .Values.container.openidClientId }}
  OPENID_PRIVATE_KEY: {{ quote .Values.container.openidPrivateKey }}
  OPENID_PUBLIC_KEY: {{ quote .Values.container.openidPublicKey }}
  COOKIE_PASSWORD: {{ quote .Values.container.cookiePassword }}
{{- end -}}
