{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-enforcement.container-secret") -}}
{{- define "aphw-ddi-enforcement.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  AZUREID_CLIENT_SECRET: {{ quote .Values.azureAppRegistration.clientSecret }}
  AZUREID_CLIENT_ID: {{ quote .Values.azureAppRegistration.clientId }}
  AZUREID_TENANT_ID: {{ quote .Values.azureAppRegistration.tenantId }}
  COOKIE_PASSWORD: {{ quote .Values.container.cookiePassword }}
{{- end -}}
