environment: production
environmentCode:
name: aphw-ddi-enforcement
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-enforcement

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: aphw-ddi-enforcement-config-map

containerSecret:
  name: aphw-ddi-enforcement-container-secret
  type: Opaque

deployment:
  replicas: 1
  minReplicas: 1
  maxReplicas: 10
  cpuThreshold: 80
  memoryThreshold: 400Mi

container:
  requestMemory: 200Mi
  requestCpu: 100m
  limitMemory: 500Mi
  limitCpu: 200m
  port: 3000
  cookiePassword: who-likes-cookies-i-like-cookies-everybody-likes-cookies
  ddiApiBaseUrl: ddi-index-api-base-url
  ddiEventsBaseUrl: ddi-events-api-base-url
  osPlacesBaseUrl: os-places-api-base-url
  osPlacesApiKey: os-places-api-key
  openidClientId: client-id
  openidPrivateKey: private-key
  openidPublicKey: public-key
  openidDiscoveryEndpoint: discovery-endpoint
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageAccountName: dummy
  messageQueueHost: namespace.servicebus.windows.net
  documentRequestQueue: aphw-ddi-certificate-request
  jwtPrivateKey: jwt-private-key
  postLogoutUrl: post-logout
  redirectUrl: authenticate
  redisHostname: dummy
  redisPort: 6379
  redisPassword: dummy

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID

ingress:
  class: nginx
  endpoint: ffc-pay-request-editor
  server: example.com

service:
  port: 80
  type: ClusterIP

